/*
 * App URI: PosMoney
 * Source Location: PosMoney.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4878), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("PosMoney", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * PosMoney.js
			 * Created at 2024. 1. 22. 오전 12:48:06.
			 *
			 * @author PC2
			 ************************************************/

			/*
			 * 서버로부터 데이터를 조회하여 그리드에 표시하는 함수
			 */
			function displayMoney() {
			    // 서브미션 생성
			    var submission = new cpr.protocols.Submission();
			    
			    // 조회할 데이터의 URL 설정
			    submission.action = "/POS/GetMoney.do"; 
			    
			    // response data의 type 설정
			    submission.responseType = "javascript";
			    
			    // 서버로 요청 전송
			    submission.send()
			    
			    submission.addEventListener("submit-success", function(e) {
			        var subMainList = e.control;
			        var jsonObj = JSON.parse(subMainList.xhr.responseText);
			        console.log(jsonObj);
			        
			        // 데이터셋 설정
			        var posMoney = app.lookup("posMoney");
			        
			        // posMoney가 null이면 0으로 설정
			        var moneyValue = jsonObj["posMoney"] !== null ? parseInt(jsonObj["posMoney"]).toLocaleString() : 0;
			        
			        // posMoney 값 설정
			        posMoney.value = moneyValue;
			    });
			}

			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad2(e){
				 displayMoney();
			}

			/*
			 * "입금하기" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
			    var button = e.control;
			   
			    var inAMT = app.lookup("inAMT").value; // inAMT 인풋박스에서 입력된 값 가져오기
			    var inContents = app.lookup("inContents").value; // inContents 인풋박스에서 입력된 값 가져오기
				var DEP_PAY_TY = "1";

			    console.log("inAMT:", inAMT);
			    console.log("inContents:", inContents);
			    console.log("DEP_PAY_TY:", DEP_PAY_TY);
				
				 // 입력값이 공백인지 확인
			    if (inAMT === "" || inContents === "") {
			        alert("입금액과 내용을 모두 입력해주세요.");
			        return;
			    }
				    
			    inAMT = inAMT.replace(/,/g, '');

			    // 콘솔에 입력된 값을 출력합니다.
			    console.log("inAMT:", inAMT);
			    
			    // 서브미션 생성
			    var submission = new cpr.protocols.Submission();
			    
			    // 요청할 URL 설정
			    submission.action = "/POS/CalculatePos.do";

			    // response data의 type 설정
			    submission.responseType = "javascript";
			    
			    submission.setParameters("AMT", inAMT);
			    submission.setParameters("CONTENTS", inContents);
			    submission.setParameters("DEP_PAY_TY", DEP_PAY_TY);

			    // 서버로 요청 전송
			    submission.send();    
			    
			    submission.addEventListener("submit-success", function(e) {
				    var subMainList = e.control;
				    alert("입금되었습니다");
				    displayMoney();
					resetContent();
				});
			    
			}

			/*
			 * "출금하기" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2(e){
				var button = e.control;
				var outAMT = app.lookup("outAMT").value; // inAMT 인풋박스에서 입력된 값 가져오기
			    var outContents = app.lookup("outContents").value; // inContents 인풋박스에서 입력된 값 가져오기

				 if (outAMT === "" || outContents === "") {
			        alert("입금액과 내용을 모두 입력해주세요.");
			        return;
			    }

				 outAMT = outAMT.replace(/,/g, '');

			    // 서브미션 생성
			    var submission = new cpr.protocols.Submission();
			    
				// 요청할 URL 설정
			    submission.action = "/POS/CalculatePos.do";

			    // response data의 type 설정
			    submission.responseType = "javascript";
				
				submission.setParameters("AMT", outAMT);
				submission.setParameters("CONTENTS", outContents);
				submission.setParameters("DEP_PAY_TY", "2");
				 
			    // 서버로 요청 전송
			    submission.send();	
			    submission.addEventListener("submit-success", function(e) {
				    var subMainList = e.control;
				    alert("출금되었습니다");
				    displayMoney();
					resetContent();
				});
				
			}

			function resetContent(){
				
				app.lookup("inAMT").value = ""; // null이면 공백 문자열로 대체
			    app.lookup("inContents").value = "";
			    app.lookup("outAMT").value = "";
			    app.lookup("outContents").value = "";
			     
			}





			/*
			 * 인풋 박스에서 value-change 이벤트 발생 시 호출.
			 * 변경된 value가 저장된 후에 발생하는 이벤트.
			 */
			function onInAMTValueChange2(e){
				var inAMT = e.control;
				var inAMT = e.control;
			    // 입력된 값 가져오기
			    var inputValue = inAMT.value.trim(); // 입력값의 앞뒤 공백을 제거합니다.
			  
			    // 입력값이 공백이 아닌 경우에만 처리
			    if(inputValue !== "") {
			        // 입력된 값이 숫자인지 확인 후 숫자로 변환
			        var numericValue = parseFloat(inputValue.replace(/[^0-9.-]+/g,""));

			        // 숫자를 지역화된 문자열로 변환하여 다시 설정
			        inAMT.value = numericValue.toLocaleString();
			    } else {
			        // 입력값이 공백인 경우는 그대로 표시
			        inAMT.value = "";
			    }
			}

			/*
			 * 인풋 박스에서 value-change 이벤트 발생 시 호출.
			 * 변경된 value가 저장된 후에 발생하는 이벤트.
			 */
			function onOutAMTValueChange(e){
				var outAMT = e.control;
				var outAMT = e.control;
			    // 입력된 값 가져오기
			    var outAMTValue = outAMT.value.trim(); // 입력값의 앞뒤 공백을 제거합니다.
			  
			    // 입력값이 공백이 아닌 경우에만 처리
			    if(outAMTValue !== "") {
			        // 입력된 값이 숫자인지 확인 후 숫자로 변환
			        var numericValue = parseFloat(outAMTValue.replace(/[^0-9.-]+/g,""));

			        // 숫자를 지역화된 문자열로 변환하여 다시 설정
			        outAMT.value = numericValue.toLocaleString();
			    } else {
			        // 입력값이 공백인 경우는 그대로 표시
			        outAMT.value = "";
			    }
			};
			// End - User Script
			
			// Header
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
			cpr.core.App.load("PosHeader", function(app) {
				if(app){
					embeddedApp_1.app = app;
				}
			});
			container.addChild(embeddedApp_1, {
				"top": "0px",
				"left": "0px",
				"width": "1024px",
				"height": "80px"
			});
			
			var group_1 = new cpr.controls.Container();
			group_1.style.css({
				"background-color" : "#E0E0E0"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "최종 잔액";
				output_1.style.css({
					"background-color" : "#BEBEBE",
					"border-radius" : "35px 35px 35px 35px",
					"font-weight" : "bold",
					"font-size" : "16px",
					"text-align" : "center"
				});
				container.addChild(output_1, {
					"top": "413px",
					"left": "334px",
					"width": "140px",
					"height": "40px"
				});
				var output_2 = new cpr.controls.Output("posMoney");
				output_2.value = "";
				output_2.style.css({
					"font-weight" : "bold",
					"font-size" : "16px",
					"text-align" : "center"
				});
				container.addChild(output_2, {
					"top": "413px",
					"left": "527px",
					"width": "182px",
					"height": "40px"
				});
				var group_2 = new cpr.controls.Container();
				group_2.style.css({
					"border-bottom-color" : "#c7c7c7",
					"border-bottom-width" : "4px",
					"border-bottom-style" : "solid"
				});
				var xYLayout_3 = new cpr.controls.layouts.XYLayout();
				group_2.setLayout(xYLayout_3);
				(function(container){
					var output_3 = new cpr.controls.Output();
					output_3.value = "입 금";
					output_3.style.css({
						"background-color" : "#BEBEBE",
						"border-radius" : "40px 40px 40px 40px",
						"font-weight" : "bold",
						"font-size" : "20px",
						"text-align" : "center"
					});
					container.addChild(output_3, {
						"top": "38px",
						"left": "41px",
						"width": "140px",
						"height": "110px"
					});
					var inputBox_1 = new cpr.controls.InputBox("inAMT");
					inputBox_1.placeholder = "금액을 입력해 주세요. ";
					inputBox_1.inputFilter = "[0-9]";
					inputBox_1.style.css({
						"border-radius" : "5px 5px 5px 5px",
						"text-align" : "right"
					});
					if(typeof onInAMTBeforeValueChange == "function") {
						inputBox_1.addEventListener("before-value-change", onInAMTBeforeValueChange);
					}
					if(typeof onInAMTChange == "function") {
						inputBox_1.addEventListener("change", onInAMTChange);
					}
					if(typeof onInAMTValueChange2 == "function") {
						inputBox_1.addEventListener("value-change", onInAMTValueChange2);
					}
					container.addChild(inputBox_1, {
						"top": "38px",
						"left": "191px",
						"width": "294px",
						"height": "48px"
					});
					var inputBox_2 = new cpr.controls.InputBox("inContents");
					inputBox_2.placeholder = "내용을 입력해 주세요.";
					inputBox_2.style.css({
						"border-radius" : "5px 5px 5px 5px",
						"text-align" : "right"
					});
					container.addChild(inputBox_2, {
						"top": "100px",
						"left": "191px",
						"width": "294px",
						"height": "48px"
					});
					var button_1 = new cpr.controls.Button();
					button_1.value = "입금하기";
					button_1.style.css({
						"font-size" : "17px"
					});
					if(typeof onButtonClick == "function") {
						button_1.addEventListener("click", onButtonClick);
					}
					container.addChild(button_1, {
						"top": "73px",
						"left": "508px",
						"width": "100px",
						"height": "40px"
					});
					var output_4 = new cpr.controls.Output();
					output_4.value = "출 금";
					output_4.style.css({
						"background-color" : "#BEBEBE",
						"border-radius" : "40px 40px 40px 40px",
						"font-weight" : "bold",
						"font-size" : "20px",
						"text-align" : "center"
					});
					container.addChild(output_4, {
						"top": "176px",
						"left": "41px",
						"width": "140px",
						"height": "110px"
					});
					var inputBox_3 = new cpr.controls.InputBox("outAMT");
					inputBox_3.placeholder = "금액을 입력해 주세요.";
					inputBox_3.inputFilter = "[0-9]";
					inputBox_3.style.css({
						"border-radius" : "5px 5px 5px 5px",
						"text-align" : "right"
					});
					if(typeof onOutAMTChange == "function") {
						inputBox_3.addEventListener("change", onOutAMTChange);
					}
					if(typeof onOutAMTValueChange == "function") {
						inputBox_3.addEventListener("value-change", onOutAMTValueChange);
					}
					container.addChild(inputBox_3, {
						"top": "176px",
						"left": "191px",
						"width": "294px",
						"height": "48px"
					});
					var inputBox_4 = new cpr.controls.InputBox("outContents");
					inputBox_4.placeholder = "내용을 입력해 주세요.";
					inputBox_4.style.css({
						"border-radius" : "5px 5px 5px 5px",
						"text-align" : "right"
					});
					container.addChild(inputBox_4, {
						"top": "238px",
						"left": "191px",
						"width": "294px",
						"height": "48px"
					});
					var button_2 = new cpr.controls.Button();
					button_2.value = "출금하기";
					button_2.style.css({
						"font-size" : "17px"
					});
					if(typeof onButtonClick2 == "function") {
						button_2.addEventListener("click", onButtonClick2);
					}
					container.addChild(button_2, {
						"top": "211px",
						"left": "508px",
						"width": "100px",
						"height": "40px"
					});
				})(group_2);
				container.addChild(group_2, {
					"top": "64px",
					"left": "195px",
					"width": "628px",
					"height": "320px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "150px",
				"left": "0px",
				"width": "1024px",
				"height": "598px"
			});
			
			var output_5 = new cpr.controls.Output("title");
			output_5.value = "시재금";
			output_5.style.css({
				"font-weight" : "bold",
				"font-size" : "25px",
				"text-align" : "center"
			});
			container.addChild(output_5, {
				"top": "90px",
				"left": "353px",
				"width": "318px",
				"height": "50px"
			});
			if(typeof onBodyLoad2 == "function"){
				app.addEventListener("load", onBodyLoad2);
			}
		}
	});
	app.title = "PosMoney";
	cpr.core.Platform.INSTANCE.register(app);
})();
